"""GENERATED by scripts/build_spell_icons.py from wago.tools game data.
Icon file name (render.worldofwarcraft.com/us/icons/56/<icon>.jpg) and in-game
description of every ability in the defensive catalog, by name."""

ICONS = {'Algari Healing Potion': 'inv_flask_red',
 'Alter Time': 'spell_mage_altertime',
 'Anti-Magic Shell': 'spell_shadow_antimagicshell',
 'Anti-Magic Zone': 'spell_deathknight_antimagiczone',
 'Ardent Defender': 'spell_holy_ardentdefender',
 'Aspect of the Turtle': 'ability_hunter_pet_turtle',
 'Astral Shift': 'ability_shaman_astralshift',
 'Aura Mastery': 'spell_holy_auramastery',
 'Barkskin': 'spell_nature_stoneclawtotem',
 'Bear Form': 'ability_racial_bearform',
 'Blazing Barrier': 'ability_mage_moltenarmor',
 'Blessing of Protection': 'spell_holy_sealofprotection',
 'Blessing of Sacrifice': 'spell_holy_sealofsacrifice',
 'Blessing of Spellwarding': 'spell_holy_blessingofprotection',
 'Blur': 'ability_demonhunter_blur',
 "Cavedweller's Delight": 'inv_alchemy_elixir_06',
 'Celestial Brew': 'ability_monk_ironskinbrew',
 'Cloak of Shadows': 'spell_shadow_nethercloak',
 'Concentrated Silvermoon Health Potion': 'inv_12_profession_alchemy_lightpotion_purple',
 'Crimson Vial': 'ability_rogue_crimsonvial',
 'Dampen Harm': 'ability_monk_dampenharm',
 'Dancing Rune Weapon': 'inv_sword_07',
 'Dark Pact': 'spell_shadow_deathpact',
 'Darkness': 'ability_demonhunter_darkness',
 'Death Pact': 'spell_shadow_deathpact',
 'Demonic Healthstone': 'warlock_bloodstone',
 'Desperate Prayer': 'spell_holy_testoffaith',
 'Die by the Sword': 'ability_warrior_challange',
 'Diffuse Magic': 'spell_monk_diffusemagic',
 'Dispersion': 'spell_shadow_dispersion',
 'Divine Protection': 'spell_holy_divineprotection',
 'Divine Shield': 'spell_holy_divineshield',
 'Earthen Wall Totem': 'spell_nature_stoneskintotem',
 'Enraged Regeneration': 'ability_warrior_focusedrage',
 'Evasion': 'spell_shadow_shadowward',
 'Exhilaration': 'ability_hunter_onewithnature',
 'Fade': 'spell_magic_lesserinvisibilty',
 'Feint': 'ability_rogue_feint',
 'Fiery Brand': 'ability_demonhunter_fierybrand',
 'Fortifying Brew': 'ability_monk_fortifyingale_new',
 'Frenzied Regeneration': 'ability_bullrush',
 'Greater Invisibility': 'ability_mage_greaterinvisibility',
 'Guardian Spirit': 'spell_holy_guardianspirit',
 'Guardian of Ancient Kings': 'spell_holy_heroism',
 'Healthstone': 'warlock_healthstone',
 'Ice Barrier': 'spell_ice_lament',
 'Ice Block': 'spell_frost_frost',
 'Ice Cold': 'spell_fire_bluefire',
 'Icebound Fortitude': 'spell_deathknight_iceboundfortitude',
 'Invigorating Healing Potion': 'inv_alchemy_70_flask04',
 'Ironbark': 'spell_druid_ironbark',
 'Last Stand': 'spell_holy_ashestoashes',
 'Lay on Hands': 'spell_holy_layonhands',
 'Lichborne': 'spell_shadow_raisedead',
 'Life Cocoon': 'ability_monk_chicocoon',
 'Metamorphosis': 'ability_demonhunter_metamorphasistank',
 'Mirror Image': 'spell_magic_lesserinvisibilty',
 'Netherwalk': 'spell_warlock_demonsoul',
 'Obsidian Scales': 'inv_artifact_dragonscales',
 'Pain Suppression': 'spell_holy_painsupression',
 'Potent Healing Potion': 'inv_alchemy_80_potion01red',
 'Power Word: Barrier': 'spell_holy_powerwordbarrier',
 'Prismatic Barrier': 'spell_magearmor',
 'Rallying Cry': 'ability_warrior_rallyingcry',
 'Renewal': 'spell_nature_natureblessing',
 'Renewing Blaze': 'ability_evoker_masterylifebinder_red',
 'Roar of Sacrifice': 'ability_hunter_fervor',
 'Rune Tap': 'spell_deathknight_runetap',
 'Shield Wall': 'ability_warrior_shieldwall',
 'Shield of Vengeance': 'ability_paladin_shieldofthetemplar',
 'Silvermoon Health Potion': 'inv_12_profession_alchemy_lightpotion_orange',
 'Spell Reflection': 'ability_warrior_shieldreflection',
 'Spirit Link Totem': 'spell_shaman_spiritlink',
 'Stone Bulwark Totem': 'ability_shaman_stonebulwark',
 'Survival Instincts': 'ability_druid_tigersroar',
 'Survival of the Fittest': 'spell_nature_spiritarmor',
 'Time Dilation': 'ability_evoker_timedilation',
 'Tombstone': 'ability_fiegndead',
 'Touch of Karma': 'ability_monk_touchofkarma',
 'Unending Resolve': 'spell_shadow_demonictactics',
 'Vampiric Blood': 'spell_shadow_lifedrain',
 'Zen Meditation': 'ability_monk_zenmeditation',
 'Zephyr': 'ability_evoker_hoverblack'}

# In-game description of each (percentages and durations exact, scaled amounts left out).
DESCRIPTIONS = {'Algari Healing Potion': 'Restores health.',
 'Alter Time': 'Alters the fabric of time, returning you to your current location and health when cast a '
               'second time, or after sec. Effect negated by long distance or death.',
 'Anti-Magic Shell': 'Surrounds you in an Anti-Magic Shell for 5 sec, absorbing up to magic damage and '
                     'preventing application of harmful magical effects.',
 'Anti-Magic Zone': 'Places an Anti-Magic Zone for 6 sec, reducing the magic damage taken by party or raid '
                    'members by 15%.',
 'Ardent Defender': 'Reduces all damage you take by 30% for 12 sec. While Ardent Defender is active, the '
                    'next attack that would otherwise kill you will instead bring you to 20% of your maximum '
                    'health.',
 'Aspect of the Turtle': 'Causes all spells and attacks to miss and reduces all damage you take by 30% for 8 '
                         'sec, but you cannot attack.',
 'Astral Shift': 'Shift partially into the elemental planes, taking 40% less damage for 12 sec.',
 'Aura Mastery': 'Empowers your chosen aura for 8 sec. Devotion Aura: Damage reduction increased. Crusader '
                 'Aura: Mount speed bonus increased. Concentration Aura: Affected allies immune to '
                 'interrupts and silences.',
 'Barkskin': 'Your skin becomes as tough as bark, reducing all damage you take by 20% and preventing damage '
             'from delaying your spellcasts. Lasts 8 sec. Usable while stunned, frozen, incapacitated, '
             'feared, or asleep, and in all shapeshift forms.',
 'Bear Form': 'Shapeshift into Bear Form, increasing armor by 220% and Stamina by 25%, granting protection '
              'from Polymorph effects, and increasing threat generation. The act of shapeshifting frees you '
              'from movement impairing effects.',
 'Blazing Barrier': 'Shields you in flame, absorbing damage for 1 min. Melee attacks against you cause the '
                    'attacker to take Fire damage.',
 'Blessing of Protection': 'Blesses a party or raid member, granting immunity to Physical damage and harmful '
                           'effects for 10 sec. Cannot be used on a target with Forbearance. Causes '
                           'Forbearance for 30 sec.',
 'Blessing of Sacrifice': 'Blesses a party or raid member, reducing their damage taken by 30%, but you '
                          'suffer of damage prevented. Last 12 sec, or until transferred damage would cause '
                          'you to fall below 20% health.',
 'Blessing of Spellwarding': 'Blesses a party or raid member, granting immunity to magical damage and '
                             'harmful effects for 10 sec. Cannot be used on a target with Forbearance. '
                             'Causes Forbearance for 30 sec. Shares a cooldown with Blessing of Protection.',
 'Blur': 'Reduces all damage taken by 25% for 10 sec.',
 "Cavedweller's Delight": 'Restores health and mana.',
 'Celestial Brew': 'A swig of strong brew that coalesces purified chi escaping your body into a celestial '
                   'guard, absorbing damage.',
 'Cloak of Shadows': 'Provides a moment of magic immunity, instantly removing all harmful spell effects. The '
                     'cloak lingers, causing you to resist harmful spells for 5 sec.',
 'Concentrated Silvermoon Health Potion': 'Restores health.',
 'Crimson Vial': 'Drink an alchemical concoction that heals you for of your maximum health over 4 sec.',
 'Dampen Harm': 'Reduces all damage you take by 20% to 50% for 10 sec, with larger attacks being reduced by '
                'more.',
 'Dancing Rune Weapon': 'Summons a rune weapon for 8 sec that mirrors your melee attacks and bolsters your '
                        'defenses. While active, you gain 30% parry chance.',
 'Dark Pact': 'Sacrifices 20% of your current health to shield you for 200% of the sacrificed health plus an '
              'additional for 20 sec. Usable while suffering from control impairing effects.',
 'Darkness': 'Summons darkness around you in a radius, granting friendly targets a 15% chance to avoid all '
             'damage from an attack. Lasts 8 sec. Chance to avoid damage increased by 100% when not in a '
             'raid.',
 'Death Pact': 'Create a death pact that heals you for 50% of your maximum health, but absorbs incoming '
               'healing equal to 30% of your max health for 15 sec.',
 'Demonic Healthstone': 'Instantly restores 25% health.',
 'Desperate Prayer': 'Increases maximum health for sec, and instantly heals you for that amount.',
 'Die by the Sword': 'Increases your parry chance by 100% and reduces all damage you take by 30% for 8 sec.',
 'Diffuse Magic': 'Reduces magic damage you take by 60% for 6 sec, and transfers all currently active '
                  'harmful magical effects on you back to their original caster if possible.',
 'Dispersion': 'Disperse into pure shadow energy, reducing all damage taken by 75% for 6 sec and healing you '
               'for of your maximum health over its duration, but you are unable to attack or cast spells. '
               'Increases movement speed by 50% and makes you immune to all movement impairing effects. '
               'Castable while stunned, feared, or silenced.',
 'Divine Protection': 'Reduces all damage you take by 20% for 8 sec. Usable while stunned.',
 'Divine Shield': 'Grants immunity to all damage, harmful effects, knockbacks and forced movement effects '
                  'for 8 sec. Cannot be used if you have Forbearance. Causes Forbearance for 30 sec.',
 'Earthen Wall Totem': 'Summons a totem at the target location with health for 15 sec. damage from each '
                       'attack against allies nearby of the totem is redirected to the totem.',
 'Enraged Regeneration': 'Reduces damage taken by 30% and Bloodthirst restores an additional 20% health for '
                         '8 sec. Usable while stunned or incapacitated.',
 'Evasion': 'Increases your dodge chance for 10 sec.',
 'Exhilaration': 'Heals you for 30% and your pet for 100% of maximum health.',
 'Fade': "Fade out, removing all your threat and reducing enemies' detection range against you for 10 sec.",
 'Feint': 'Performs an evasive maneuver, ?a79008[reducing damage taken from area-of-effect attacks by 40% '
          'and all other damage taken][reducing damage taken from area-of-effect attacks by 40%] for 6 sec.',
 'Fiery Brand': 'Brand yourself and an enemy target with demonic symbols, reducing the damage you take by '
                '40% and instantly dealing Fire damage to the enemy.',
 'Fortifying Brew': 'Turns your skin to stone for 15 sec.',
 'Frenzied Regeneration': 'Heals you for health over 3 sec.',
 'Greater Invisibility': 'Makes you invisible and untargetable for 20 sec, removing all threat. Any action '
                         'taken cancels this effect.',
 'Guardian Spirit': 'Calls upon a guardian spirit to watch over the friendly target for 10 sec, increasing '
                    'healing received by 60%. If the target would die, the Spirit sacrifices itself and '
                    'restores the target to 40% health. Castable while stunned. Cannot save the target from '
                    'massive damage.',
 'Guardian of Ancient Kings': 'Empowers you with the spirit of ancient kings, reducing all damage you take '
                              'by 50% for 8 sec.',
 'Healthstone': 'Instantly restores 25% health.',
 'Ice Barrier': 'Shields you with ice, absorbing damage for 1 min. Melee attacks against you reduce the '
                "attacker's movement speed by 50%.",
 'Ice Block': 'Encases you in a block of ice, protecting you from all attacks and damage for 10 sec, but '
              'during that time you cannot attack, move, or cast spells. Causes Hypothermia, preventing you '
              'from recasting Ice Block for 30 sec.',
 'Ice Cold': 'Your blood runs cold, reducing all damage you take by 70% for 6 sec. Causes Hypothermia, '
             'preventing you from recasting Ice Cold for 30 sec.',
 'Icebound Fortitude': 'Your blood freezes, granting immunity to Stun effects and reducing all damage you '
                       'take by 30% for 8 sec.',
 'Invigorating Healing Potion': 'Restores health.',
 'Ironbark': "The target's skin becomes as tough as Ironwood, reducing damage taken by 20% for 12 sec.",
 'Last Stand': 'Increases maximum health by 30% for 8 sec and instantly heals you for that amount.',
 'Lay on Hands': 'Heals a friendly target for an amount equal to 100% your maximum health. Cannot be used on '
                 'a target with Forbearance. Causes Forbearance for 30 sec.',
 'Lichborne': 'Draw upon unholy energy to become Undead for 10 sec, increasing Leech by 6% and making you '
              'immune to Charm, Fear, and Sleep.',
 'Life Cocoon': 'Encases the target in a cocoon of Chi energy for 12 sec, absorbing damage and increasing '
                'all healing over time received by 50%.',
 'Metamorphosis': 'Transform to demon form for 15 sec, increasing current health by 40%, healing for that '
                  'amount, and increasing Armor by 200%.',
 'Mirror Image': 'Creates copies of you nearby for 15 sec, which cast spells and attack your enemies. While '
                 'active, you generate significantly reduced threat. Taking direct damage will cause one of '
                 'your images to dissipate.',
 'Netherwalk': 'Slip into the nether when you active Blur, increasing movement speed by 100% and becoming '
               'immune to damage for 2.5 sec.',
 'Obsidian Scales': 'Reinforce your scales, reducing damage taken by 30%. Lasts 12 sec.',
 'Pain Suppression': 'Reduces all damage taken by a friendly target by 40% for 8 sec. Castable while '
                     'stunned.',
 'Potent Healing Potion': 'Restores health.',
 'Power Word: Barrier': 'Summons a holy barrier to protect all allies at the target location for 10 sec, '
                        'reducing all damage taken by 20% and preventing damage from delaying spellcasting.',
 'Prismatic Barrier': 'Shields you with an arcane force, absorbing damage and reducing magic damage taken by '
                      '15% for 1 min. The duration of harmful Magic effects against you is reduced by 25%.',
 'Rallying Cry': 'Lets loose a rallying cry, granting all party or raid members within 40 yards 10% '
                 'temporary and maximum health for 10 sec. Health granted increased by 50% when not in a '
                 'raid.',
 'Renewal': 'Instantly heals you for 30% of maximum health. Usable in all shapeshift forms.',
 'Renewing Blaze': 'Obsidian Scales surrounds you with a Renewing Blaze, causing 100% of the damage it '
                   'prevented to be healed back over 8 sec.',
 'Roar of Sacrifice': 'Instructs your pet to protect a friendly target, reducing their damage taken by 15%, '
                      'but 50% of all damage taken by that target is transferred to your pet. Lasts 10 sec '
                      "or until your pet's health drops below 25%.",
 'Rune Tap': 'Reduces all damage taken by 20% for 4 sec.',
 'Shield Wall': 'Reduces all damage you take by 40% for 8 sec.',
 'Shield of Vengeance': 'Creates a barrier of holy light that absorbs damage for 10 sec. When the shield '
                        'expires, it bursts to inflict Holy damage equal to the total amount absorbed, '
                        'divided among all nearby enemies.',
 'Silvermoon Health Potion': 'Restores health.',
 'Spell Reflection': 'Raise your, reflecting on you and reducing magic damage you take by 20% for 5 sec.',
 'Spirit Link Totem': 'Summons a totem at the target location for 6 sec, which reduces damage taken by all '
                      'party and raid members within 10 yards by 10%. Immediately and every 1 sec, the '
                      'health of all affected players is redistributed evenly.',
 'Stone Bulwark Totem': 'Summons a totem at your feet that grants you an absorb shield preventing damage for '
                        '15 sec, and an additional every 5 sec for 30 sec.',
 'Survival Instincts': 'Reduces all damage you take by 50% for 6 sec.',
 'Survival of the Fittest': 'Reduces all damage you and your pet take by 30% for 6 sec.',
 'Time Dilation': 'Stretch time around an ally for the next 8 sec, causing 50% of damage they would take to '
                  'instead be dealt over 8 sec.',
 'Tombstone': 'Consume up to Bone Shield charges. For each charge consumed, you gain Runic Power and absorb '
              'damage equal to 6% of your maximum health for 8 sec.',
 'Touch of Karma': 'Absorbs all damage taken for 10 sec, up to 50% of your maximum health, and redirects 70% '
                   'of that amount to the enemy target as Nature damage over 6 sec.',
 'Unending Resolve': 'Hardens your skin, reducing all damage you take by 25% and granting immunity to '
                     'interrupt, silence, and pushback effects for 8 sec.',
 'Vampiric Blood': 'Embrace your undeath, increasing your maximum health by 30% and increasing all healing '
                   'and absorbs received by 30% for 10 sec.',
 'Zen Meditation': 'Reduces all damage taken by 60% for 8 sec. Being hit by a melee attack, or taking '
                   'another action will cancel this effect.',
 'Zephyr': 'Conjure an updraft to lift you and your nearest allies within 20 yds into the air, reducing '
           'damage taken from area-of-effect attacks by 20% and increasing movement speed by 30% for 8 sec.'}
