"""Regenerate backend/boss_spell_flags.py from the live game data on wago.tools.

Lists boss damage spells the game flags as unaffected by immunities
(SpellMisc Attributes_0 & 0x20000000, "no immunities"), so "would Ice Block /
Divine Shield have saved them" is never a yes against them. Stored in the repo
so the analysis never has to look them up.

Covered: every damage spell from The War Within onward (spell ID 400000+),
plus every spell in the Dungeon Journal of the raids in analysis.RAID_ENCOUNTERS
and the spells those trigger. Rerun when a new raid or patch comes out:

    python backend/scripts/build_boss_spell_flags.py

Needs network access to wago.tools.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from analysis import RAID_ENCOUNTERS  # noqa: E402
from build_defensive_catalog import table  # noqa: E402

NO_IMMUNITIES = 0x20000000
FIRST_TWW_SPELL = 400_000
SCHOOL_DAMAGE, HEALTH_LEECH = "2", "9"
DAMAGE_AURAS = {"3", "53", "89"}      # periodic damage, periodic leech, periodic %-of-health damage


def main():
    effects = {}
    for r in table("SpellEffect"):
        if r["DifficultyID"] == "0":
            effects.setdefault(int(r["SpellID"]), []).append(r)
    damaging = {s for s, es in effects.items()
                if any(e["Effect"] in (SCHOOL_DAMAGE, HEALTH_LEECH) or e["EffectAura"] in DAMAGE_AURAS for e in es)}

    encounters = set().union(*RAID_ENCOUNTERS.values())
    journal = {int(r["ID"]): int(r["DungeonEncounterID"]) for r in table("JournalEncounter")}
    seen = set()
    stack = [int(r["SpellID"]) for r in table("JournalEncounterSection")
             if journal.get(int(r["JournalEncounterID"])) in encounters and r["SpellID"] != "0"]
    while stack:
        sid = stack.pop()
        if sid in seen:
            continue
        seen.add(sid)
        stack += [int(e["EffectTriggerSpell"]) for e in effects.get(sid, ()) if int(e["EffectTriggerSpell"] or 0)]
    found_encounters = encounters & set(journal.values())
    if found_encounters != encounters:
        print(f"Warning: encounters missing from the journal: {sorted(encounters - found_encounters)}")

    flagged = set()
    for r in table("SpellMisc"):
        if r["DifficultyID"] == "0" and int(r["Attributes_0"]) & NO_IMMUNITIES:
            flagged.add(int(r["SpellID"]))
    ignores = sorted(s for s in flagged & damaging if s >= FIRST_TWW_SPELL or s in seen)

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "boss_spell_flags.py")
    with open(out, "w") as f:
        f.write('"""GENERATED by scripts/build_boss_spell_flags.py from wago.tools game data.\n'
                'Damage spells that hit through immunities (Ice Block, Divine Shield, ...)."""\n\n')
        f.write("IGNORES_IMMUNITY = frozenset({\n")
        for i in range(0, len(ignores), 8):
            f.write("    " + ", ".join(str(s) for s in ignores[i:i + 8]) + ",\n")
        f.write("})\n")
    print(f"Wrote {len(ignores)} spells to {os.path.normpath(out)}")


if __name__ == "__main__":
    main()
