"""Regenerate backend/raid_wide_damage.py: boss abilities that hit most of the raid at once.

    WCL_CLIENT_ID=... WCL_CLIENT_SECRET=... python backend/scripts/build_raid_wide.py

A death is only "worn down by" an ability (rot) when that ability is raid-wide
damage the healers have to keep up with, not a soak or a mechanic the player
walked into (Toxic Droplets, Immortal Coil's well). For every encounter in
analysis.RAID_ENCOUNTERS this reads the damage taken in Mythic kills by a few
guilds (WCL fightRankings), groups each ability's hits into occurrences (hits
within OCCURRENCE_MS of each other) and measures the share of the raid each
occurrence hits. An ability is raid-wide when the median occurrence hits at
least RAID_WIDE_SHARE of the raid. Rerun for a new raid (about 10 WCL points
per encounter).
"""
import os
import statistics
import sys
from collections import defaultdict

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

import defensives  # noqa: E402
from analysis import RAID_ENCOUNTERS  # noqa: E402
from warcraftlogs import get_access_token, get_fights, graphql_query  # noqa: E402

KILLS_PER_ENCOUNTER = 3
OCCURRENCE_MS = 1_000
MIN_OCCURRENCES = 3
RAID_WIDE_SHARE = 0.5
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "raid_wide_damage.py")


def kills(token, encounter):
    data = graphql_query(token, """query($e: Int!) { worldData { encounter(id: $e) { name
        fightRankings(difficulty: 5, page: 1) } } }""", {"e": encounter})
    enc = (data.get("worldData") or {}).get("encounter") or {}
    seen, out = set(), []
    for r in (enc.get("fightRankings") or {}).get("rankings") or []:
        guild = (r.get("guild") or {}).get("id")
        if guild in seen:
            continue
        seen.add(guild)
        out.append((r["report"]["code"], r["report"]["fightID"]))
        if len(out) == KILLS_PER_ENCOUNTER:
            break
    return enc.get("name"), out


def shares(token, code, fight_id):
    """{abilityID: (name, [share of the raid hit per occurrence])} for one kill."""
    meta = get_fights(token, code)
    fight = next((f for f in meta["fights"] if f["id"] == fight_id), None)
    if not fight or not fight["friendlyPlayers"]:
        return {}
    players = set(fight["friendlyPlayers"])
    events = defensives._fetch_blocks(token, code, {"k": ([fight_id], fight["start_time"], fight["end_time"] + 1,
                                                          "DamageTaken", None)})["k"]
    hits = defaultdict(list)
    for e in events:
        if e.get("type") == "damage" and e.get("targetID") in players and not e.get("sourceIsFriendly") \
                and e.get("sourceID") not in players:
            hits[e.get("abilityGameID")].append((e["timestamp"], e["targetID"]))
    out = {}
    for aid, hs in hits.items():
        hs.sort()
        occurrences, cur = [], []
        for t, p in hs:
            if cur and t - cur[0][0] > OCCURRENCE_MS:
                occurrences.append(cur)
                cur = []
            cur.append((t, p))
        occurrences.append(cur)
        out[aid] = (meta["abilities"].get(aid, str(aid)),
                    [len({p for _, p in o}) / len(players) for o in occurrences])
    return out


def main():
    token = get_access_token(os.environ["WCL_CLIENT_ID"], os.environ["WCL_CLIENT_SECRET"])
    found = {}                               # abilityID -> (name, boss, share)
    for encounter in sorted(set().union(*RAID_ENCOUNTERS.values())):
        boss, sample = kills(token, encounter)
        per = defaultdict(list)              # abilityID -> per-kill median shares
        names = {}
        for code, fight_id in sample:
            for aid, (name, s) in shares(token, code, fight_id).items():
                if len(s) >= MIN_OCCURRENCES:
                    per[aid].append(statistics.median(s))
                    names[aid] = name
        wide = {aid: statistics.median(v) for aid, v in per.items() if statistics.median(v) >= RAID_WIDE_SHARE}
        print(f"{boss} ({encounter}), {len(sample)} kills: "
              + (", ".join(f"{names[a]} {s:.0%}" for a, s in sorted(wide.items(), key=lambda x: -x[1])) or "none"))
        for aid, s in wide.items():
            found[aid] = (names[aid], boss, round(s, 2))
    with open(OUT, "w", newline="\n") as f:
        f.write('"""GENERATED by scripts/build_raid_wide.py from Mythic kills on WarcraftLogs.\n'
                'Boss abilities whose median occurrence hits at least half the raid at once:\n'
                'raid-wide damage, the only kind a death can be "worn down by" (rot)."""\n\n'
                "RAID_WIDE = {\n")
        for aid, (name, boss, s) in sorted(found.items(), key=lambda x: (x[1][1], x[1][0])):
            f.write(f"    {aid}: {s},  # {name} ({boss})\n")
        f.write("}\n")
    print(f"Wrote {len(found)} abilities to {OUT}")


if __name__ == "__main__":
    main()
