"""Regenerate backend/spell_icons.py from the live game data on wago.tools.

The icon of every defensive, external and consumable in the defensive catalog
(all patches), by name, so the results page can show one even when nobody used
that ability in the report (the report's own ability list only has the ones
that were cast). Icons come from SpellMisc (SpellIconFileDataID) and
ManifestInterfaceData (file ID -> icon file name). Rerun after rebuilding the
catalog:

    python backend/scripts/build_spell_icons.py

Needs network access to wago.tools.
"""
import os
import pprint
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from build_defensive_catalog import patches, table  # noqa: E402
from defensive_catalog import CATALOGS  # noqa: E402


def icons_for(build):
    files = {int(r["ID"]): r["FileName"] for r in table("ManifestInterfaceData", build)
             if r["FilePath"].lower().startswith("interface\\icons")}
    out = {}
    for r in table("SpellMisc", build):
        if r["DifficultyID"] == "0" and int(r["SpellIconFileDataID"] or 0) in files:
            out[int(r["SpellID"])] = files[int(r["SpellIconFileDataID"])].rsplit(".", 1)[0].lower().replace(" ", "")
    return out


def main():
    spells = {}          # name -> spell IDs, newest patch first
    for patch in sorted(CATALOGS, key=lambda p: [int(x) for x in p.split(".")], reverse=True):
        for sid, entry in CATALOGS[patch].items():
            spells.setdefault(entry["name"], [])
            if sid not in spells[entry["name"]]:
                spells[entry["name"]].append(sid)
    live = icons_for(patches()[-1][2])
    icons, missing = {}, []
    for name, sids in sorted(spells.items()):
        icon = next((live[s] for s in sids if s in live), None)
        if icon:
            icons[name] = icon
        else:
            missing.append(name)
    if missing:
        print("No icon in the live build: " + ", ".join(missing))
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "spell_icons.py")
    with open(out, "w") as f:
        f.write('"""GENERATED by scripts/build_spell_icons.py from wago.tools game data.\n'
                'Icon file name of every ability in the defensive catalog, by name\n'
                '(render.worldofwarcraft.com/us/icons/56/<icon>.jpg)."""\n\n')
        f.write("ICONS = " + pprint.pformat(icons, width=110) + "\n")
    print(f"Wrote {len(icons)} icons to {os.path.normpath(out)}")


if __name__ == "__main__":
    main()
