"""Regenerate backend/spell_icons.py from the live game data on wago.tools.

The icon and in-game description of every defensive, external and consumable
in the defensive catalog (all patches), by name, for the results page
tooltips. Icons show even when nobody used that ability in the report (the
report's own ability list only has the ones that were cast). Icons come from
SpellMisc (SpellIconFileDataID) and ManifestInterfaceData (file ID -> icon
file name); descriptions are filled in like the boss spell descriptions
(scripts/build_boss_spell_text.py: exact percentages and durations, scaled
amounts left out). Rerun after rebuilding the catalog:

    python backend/scripts/build_spell_icons.py

Needs network access to wago.tools.
"""
import os
import pprint
import sys

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from build_boss_spell_text import Data, render  # noqa: E402
from build_defensive_catalog import patches, table  # noqa: E402
from defensive_catalog import CATALOGS  # noqa: E402


def icons_for(build):
    files = {int(r["ID"]): r["FileName"] for r in table("ManifestInterfaceData", build)
             if r["FilePath"].lower().startswith("interface\\icons")}
    out = {}
    for r in table("SpellMisc", build):
        if r["DifficultyID"] == "0" and int(r["SpellIconFileDataID"] or 0) in files:
            out[int(r["SpellID"])] = files[int(r["SpellIconFileDataID"])].rsplit(".", 1)[0].lower().replace(" ", "")
    return out


def item_icons_for(build, spell_names):
    """Potions: their item's icon (what players see in their bags), not the generic spell icon.

    {potion name: icon}, from the potion's own items (same name) that cast that spell.
    """
    files = {int(r["ID"]): r["FileName"] for r in table("ManifestInterfaceData", build)
             if r["FilePath"].lower().startswith("interface\\icons")}
    effect_spell = {r["ID"]: int(r["SpellID"]) for r in table("ItemEffect", build) if int(r["SpellID"]) in spell_names}
    item_spell = {int(r["ItemID"]): effect_spell[r["ItemEffectID"]]
                  for r in table("ItemXItemEffect", build) if r["ItemEffectID"] in effect_spell}
    names = {int(r["ID"]): r["Display_lang"] for r in table("ItemSparse", build) if int(r["ID"]) in item_spell}
    out = {}
    for r in table("Item", build):
        item = int(r["ID"])
        sid = item_spell.get(item)
        if sid and names.get(item) == spell_names[sid] and int(r["IconFileDataID"] or 0) in files:
            out.setdefault(spell_names[sid], files[int(r["IconFileDataID"])].rsplit(".", 1)[0].lower().replace(" ", ""))
    return out


def main():
    spells = {}          # name -> spell IDs, newest patch first
    for patch in sorted(CATALOGS, key=lambda p: [int(x) for x in p.split(".")], reverse=True):
        for sid, entry in CATALOGS[patch].items():
            spells.setdefault(entry["name"], [])
            if sid not in spells[entry["name"]]:
                spells[entry["name"]].append(sid)
    build = patches()[-1][2]
    live, data = icons_for(build), Data(build)
    potions = {sid: e["name"] for c in CATALOGS.values() for sid, e in c.items() if e["kind"] == "potion"}
    item_icons = item_icons_for(build, potions)
    icons, texts, missing, no_text = {}, {}, [], []
    for name, sids in sorted(spells.items()):
        icon = item_icons.get(name) or next((live[s] for s in sids if s in live), None)
        if icon:
            icons[name] = icon
        else:
            missing.append(name)
        text = next((t for s in sids if (t := render(data, s))), None)
        if text:
            texts[name] = text
        else:
            no_text.append(name)
    if missing:
        print("No icon in the live build: " + ", ".join(missing))
    if no_text:
        print("No description in the live build: " + ", ".join(no_text))
    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "spell_icons.py")
    with open(out, "w") as f:
        f.write('"""GENERATED by scripts/build_spell_icons.py from wago.tools game data.\n'
                'Icon file name (render.worldofwarcraft.com/us/icons/56/<icon>.jpg) and in-game\n'
                'description of every ability in the defensive catalog, by name."""\n\n')
        f.write("ICONS = " + pprint.pformat(icons, width=110) + "\n\n")
        f.write("# In-game description of each (percentages and durations exact, scaled amounts left out).\n")
        f.write("DESCRIPTIONS = " + pprint.pformat(texts, width=110) + "\n")
    print(f"Wrote {len(icons)} icons and {len(texts)} descriptions to {os.path.normpath(out)}")


if __name__ == "__main__":
    main()
